<?php
$lang = array(

'blogger_api_module_name'						=>		'Blogger API',
'blogger_api_module_description'						=>		'Модуль Blogger API',
'blogger_api_home'						=>		'Панель управления',
'api_urls'						=>		'Просмотр ссылок для Blogger API',
'invalid_access'						=>		'Отказ в доступе',
'no_channels_found'						=>		'No Channels found for this user.',
'invalid_channel'						=>		'Invalid Channel Selection',
'invalid_categories'						=>		'Неправильный выбор категории',
'no_entries_found'						=>		'Записи не найдены',
'no_entry_found'						=>		'Запись в базе данных не найдена',
'unauthorized_action'						=>		'Вы не авторизованы для выполнения этой операции.',
'entry_uneditable'						=>		'Вы не можете редактировать эту запись. Проверьте наличие соответствующих разрешений для группы участников.',
'channeler_configurations'						=>		'Настроки Blogger API',
'blogger_config_name'						=>		'Название',
'blogger_config_url'						=>		'URL',
'no_blogger_configs'						=>		'There are currently no Blogger API Configurations',
'blogger_delete_confirm'						=>		'Удалить настройки Blogger API',
'blogger_deleted'						=>		'Настройка Blogger API удалена',
'bloggers_deleted'						=>		'Настройки Blogger API удалены',
'blogger_delete_question'						=>		'Вы действительно хотите удалить выбранные настройки Blogger API?',
'delete'						=>		'Удалить',
'new_config'						=>		'Новая настройка',
'modify_config'						=>		'Изменение настроек',
'configuration_options'						=>		'Опции настроек',
'blogger_pref_name'						=>		'Наименование',
'blogger_default_field'						=>		'Поле по умолчанию',
'blogger_default_field_subtext'						=>		'Если не указано другое поле, контент нового или редактируемого материала будет размещен в этом поле в виде текстового блока, без разбиения его на отдельные части.  Убедитесь в наличии указываемого поля в соответствующем блоге.',
'blogger_html_format'						=>		'HTML-форматирование',
'blogger_html_format_subtext'						=>		'Хотите ли Вы, чтобы при запросе материалов совместимыми с Blogger API программами-клиентами контент передавался в них с ограничениями HTML-форматирования? ',
'blogger_text_format'						=>		'Передача в редактор персонального компьютера (программу-клиент) текста в заданном формате',
'blogger_text_format_subtext'						=>		'When editing entries using your desktop program, would you like the text 
formatted according to your chosen preferences?  Normally this will be set to 
\'no\'',
'blogger_parse_type'						=>		'Настройка форматирования текста',
'blogger_parse_type_subtext'						=>		'(Связано со следующими двумя опциями!) Отображение контента материала будет таким, как он будет выглядеть на веб-странице &#8211; с применением кода pMCode и выводом директорий файлов.',
'html_format_none'						=>		'Разрешить весь HTML',
'html_format_safe'						=>		'Разрешить только безопасный HTML',
'html_format_all'						=>		'Преобразовывать HTML в числовые коды',
'blogger_block_entry'						=>		'Отправлять материал в виде текстового блока',
'blogger_block_entry_subtext'						=>		'Перед отправкой в программу-клиент API объединит материал всех отдельных полей в единый текст без деления его на поля.',
'yes'						=>		'Да',
'no'						=>		'Нет',
'blogger_mising_fields'						=>		'Поле не заполнено',
'configuration_created'						=>		'Настройка сохранена',
'configuration_updated'						=>		'Настройка обновлена',
'blogger_create_new'						=>		'Создать новую настройку',
''						=>		'',
// IGNORE
''=>'');
/* End of file blogger_api_lang.php */