<?php
$lang = array(

'referrer_module_name'						=>		'Рефереры',
'referrer_module_description'						=>		'Модуль отслеживания рефереров',
'referrer_preferences'						=>		'Настройки рефереров',
'referrer_ip'						=>		'IP рефереров',
'referrer_date'						=>		'Дата просмотра',
'ref_ip'						=>		'IP-адрес',
'ref_user_agent'						=>		'User Agent',
'ref_url'						=>		'URL',
'ref_type'						=>		'Тип',
'referrers'						=>		'Рефереры',
'view_referrers'						=>		'Просмотр рефереров',
'clear_referrers'						=>		'Удалить информацию о реферерах',
'referrer_from'						=>		'Реферер &#8211; откуда:',
'referrer_to'						=>		'Реферер &#8211; куда:',
'no_referrers'						=>		'Нет рефереров',
'referrer_no_results'						=>		'Нет совпадений по заданным вами критериям',
'total_referrers'						=>		'Всего рефереров:',
'save_instructions'						=>		'Сколько хранить записей о последних реферерах?',
'referrers_deleted'						=>		'Информация о реферерах удалена',
'referrer_deleted'						=>		'Информация о реферере была удалена',
'delete_confirm'						=>		'Подтверждение удаления',
'referrer_delete_question'						=>		'Вы действительно хотите удалить информацию о выбранных реферерах?',
'blacklist_question'						=>		'В дополнение к удалению информации об этих реферерах Вы можете также:',
'add_urls'						=>		'Добавить их URL в черный список и удалить других рефереров с подобным URL-адресом?',
'add_and_blacklist_urls'						=>		'Добавить их URL в черный список и удалить других рефереров с подобным URL-адресом?',
'add_ips'						=>		'Добавить IP-адреса в черный список и удалить других рефереров с таким же IP?',
'add_and_blacklist_ips'						=>		'Добавить IP адрес в чёрный список и удалить других рефералов с таким же IP?',
'add_agents'						=>		'Добавить User Agent в черный список и удалить других рефереров с таким же User Agent?',
'add_and_blacklist_agents'						=>		'Добавить браузер в черный список и удалить других рефереров с таким же браузером?',
''						=>		'',
// IGNORE
''=>'');
/* End of file referrer_lang.php */